language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

install: composer install --no-interaction --classmap-authoritative

script: vendor/bin/phpunit --coverage-clover tests/logs/clover.xml --configuration phpunit.xml

after_success: vendor/bin/php-coveralls -v

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer
