language: php

env: COMPOSER_FLAGS="--no-interaction --classmap-authoritative --no-suggest"

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly
  
matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly
      env: COMPOSER_FLAGS="${COMPOSER_FLAGS} --ignore-platform-reqs"

install: composer install ${COMPOSER_FLAGS}

script: vendor/bin/phpunit --configuration phpunit.xml

after_success: vendor/bin/php-coveralls --verbose

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer
