language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

install: composer install --no-interaction --classmap-authoritative --no-suggest

script: vendor/bin/phpunit --configuration phpunit.xml

after_success: vendor/bin/php-coveralls --verbose

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer
