language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

install: composer install --no-interaction --classmap-authoritative

script: vendor/bin/phpunit --configuration phpunit.xml

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer
