language: php

php:
  - '7.1'
  - '7.2'

install: composer install --no-interaction --classmap-authoritative

script: vendor/bin/phpunit --configuration phpunit.xml

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer
