language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

install:
  - composer install --no-interaction --classmap-authoritative --no-suggest
  - composer require --no-interaction php-coveralls/php-coveralls:^2.0

script:
  - chmod +x run-phpunit.sh
  - ./run-phpunit.sh

after_success: vendor/bin/php-coveralls --verbose

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer
