language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm

install: composer install --no-interaction --classmap-authoritative

script: vendor/bin/phpunit --configuration phpunit.xml

after_success:
  - composer require --no-interaction php-coveralls/php-coveralls:^2.0
  - vendor/bin/php-coveralls --verbose

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer
