version: 2.1

orbs:
  composer: stockfiller/composer@0.0.38
  php-cs-fixer: stockfiller/php-cs-fixer@0.0.16
  phpunit: stockfiller/phpunit@0.0.13

executors:
  default:
    docker:
      - image: php:7.4-alpine
    resource_class: small
  matrix:
    docker:
      - image: php:7.4-alpine
      - image: php:8.0-alpine
    resource_class: small

commands:
  install_xdebug:
    steps:
      - run:
          name: Install PCOV and Git
          command: |-
            apk add --update --no-cache ${PHPIZE_DEPS} git
            pecl install pcov-1.0.6
            docker-php-ext-enable pcov

workflows:
  master:
    jobs:
      - phpunit/test: &unit-tests
          name: unit-tests
          executor: matrix
          pre-steps:
            - composer/install_bin
          filters:
            branches:
              only: master
  branch:
    jobs:
      - php-cs-fixer/fix:
          name: coding-standards
          executor: default
          rules: "@PSR2"
          pre-steps:
            - composer/install_bin
          filters: &branch-filters
            branches:
              ignore: master
      - phpunit/test:
          <<: *unit-tests
          flags: --coverage-clover coverage/clover.xml
          pre-steps:
            - install_xdebug
            - composer/install_bin
          post-steps:
            - run: php vendor/bin/php-coveralls --verbose
            - store_artifacts:
                path: coverage/clover.xml
          filters: *branch-filters
          requires:
            - coding-standards
