version: 2.1
executors:
  default:
    docker:
      - image: cimg/php:7.0
      - image: cimg/php:7.1
      - image: cimg/php:7.2
      - image: cimg/php:7.3
      - image: cimg/php:7.4
orbs:
  php-coveralls: nekman/php-coveralls@0.0.1
  php-cs-fixer: stockfiller/php-cs-fixer@0.0.10
workflows:
  foo:
    jobs:
      - php-coveralls/test_and_upload
      - php-cs-fixer/fix
