version: 2.1

orbs:
  composer: stockfiller/composer@0.0.38
  php-cs-fixer: stockfiller/php-cs-fixer@0.0.13
  phpunit: stockfiller/phpunit@0.0.13

executors:
  default:
    docker:
      - image: php:7.4-alpine
  matrix:
    docker:
      - image: php:7.4-alpine
      - image: php:8.0-alpine

commands:
  install_xdebug:
    steps:
      - run: |
          apk add --update --no-cache ${PHPIZE_DEPS} wget
          yes | pecl install xdebug-3.0.2
          docker-php-ext-enable xdebug

workflows:
  master:
    jobs:
      - phpunit/test: &test
          executor: default
          pre-steps:
            - composer/install_bin
          filters:
            branches:
              only: master
  branch:
    jobs:
      - php-cs-fixer/fix:
          name: coding-standards
          executor: default
          pre-steps:
            - composer/install_bin
          filters: &branch-filters
            branches:
              ignore: master
      - phpunit/test:
          <<: *test
          flags: --coverage-clover coverage/clover.xml
          pre-steps:
            - install_xdebug
            - composer/install_bin
          post-steps:
            - run: php vendor/bin/php-coveralls --coverage_clover coverage/clover.xml
            - store_artifacts:
                path: coverage/clover.xml
          filters: *branch-filters
          requires:
            - coding-standards
